### ISSUE TITLE
Image credit text shifts left when other content is hidden

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#37]
The image credit text shifts to the left as the rest of the content on the page is hidden (to showcase the background image).

This appears to be the result of using the jQuery `.fadeOut()` method, which adds a style of `display: none;` to all matched elements, removing them from the flow of the page. Removing the `settings-icon-wrapper` `div` causes the bottom row to shift left.

David has already proposed that we use;
> the `hidden` utility we have for `initial-wrapper` & `main-wrapper` instead of inline `style` attribute

Can we use the same technique to resolve this issue?

**Comment by DavidLarsKetch** [comment]
Working on this one now.

**Comment by DavidLarsKetch** [comment]
Not sure how referencing issues in a commit works still, but `issue/37` resolves this issue.
`issue/37` branches from `development`, which has not been merged with `feature/settings`, nonetheless, there should not be any shifting since `fadeTo` does not change the CSS `display` rule, only `opacity`. Moreover, though there is no `(".settings-icon-wrapper")` currently in `development`, once the merge takes place, hovering over the credits will *not* cause the gear icon to fade. Thought that looked better than having it fade away.
